TELEGRAM_CHANNELS = [
    {
        "slug": "texnomart",
        "name": "Texnomart",
        "channel": "texnomart",
        "url": "https://t.me/s/texnomart",
        "category": "electronics",
        "color": "#3b82f6",
    },
    {
        "slug": "asaxiy",
        "name": "Asaxiy",
        "channel": "asaxiyuz",
        "url": "https://t.me/s/asaxiyuz",
        "category": "electronics",
        "color": "#8b5cf6",
    },
    {
        "slug": "mediapark",
        "name": "Mediapark",
        "channel": "mediapark_uzb",
        "url": "https://t.me/s/mediapark_uzb",
        "category": "electronics",
        "color": "#ec4899",
    },
    {
        "slug": "goodzone",
        "name": "Goodzone",
        "channel": "goodzone_uzbekistan",
        "url": "https://t.me/s/goodzone_uzbekistan",
        "category": "electronics",
        "color": "#ef4444",
    },
    {
        "slug": "elmakon",
        "name": "Elmakon",
        "channel": "elmakonuz",
        "url": "https://t.me/s/elmakonuz",
        "category": "electronics",
        "color": "#f97316",
    },
    {
        "slug": "korzinka",
        "name": "Korzinka",
        "channel": "korzinka_uz",
        "url": "https://t.me/s/korzinka_uz",
        "category": "grocery",
        "color": "#22c55e",
    },
    {
        "slug": "makro",
        "name": "Makro",
        "channel": "makrosupermarket",
        "url": "https://t.me/s/makrosupermarket",
        "category": "grocery",
        "color": "#eab308",
    },
    {
        "slug": "havas",
        "name": "Havas",
        "channel": "havasuz",
        "url": "https://t.me/s/havasuz",
        "category": "grocery",
        "color": "#10b981",
    },
]
